### ISSUE TITLE
gzip data before sending to S3 to save on storage costs

### ISSUE THREAD

**Issue by deansheather** [whats-this/api#10]
Obviously, this idea needs testing in regards to working with Cloudfront but I think we can get it working.

More information: http://www.rightbrainnetworks.com/blog/serving-compressed-gzipped-static-files-from-amazon-s3-or-cloudfront/

**Comment by sr229** [comment]
honestly this is a must-have 

if someone can create a actual working draft, I'll be happy to test it

**Comment by deansheather** [comment]
Technically, we should be able to just set the `Content-Encoding` metadata parameter (header) to `gzip` when we store to S3, and upload gzipped data instead of the regular data.

Still need to perform tests, though. I guess I can force-upload some gzipped files with the correct headers to see how CloudFront handles it. Currently, CloudFront is gzipping on the fly with supported browsers, I'd like to see how it reacts when the origin sends a gzipped file and the client doesn't `Accept-Encoding` of gzip. Hopefully CloudFront will decompress the data and send that. It'd be a shame if we have to make a proxy for this to work.

**Comment by deansheather** [comment]
Another handy resource for later: http://stackoverflow.com/questions/5442011/serving-gzipped-css-and-javascript-from-amazon-cloudfront-via-s3
